name: operational-monad
version: 0.0.1.0
ghc-options: -Wall -Werror -Wno-unused-matches -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-import-lists

dependencies: 
  - base

library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  operational-monad-exe:
    source-dirs: app
    main: Main.hs 
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: operational-monad

tests:
  operational-monad-test:
    source-dirs: test
    main: Spec.hs
    dependencies: 
      - operational-monad
      - QuickCheck
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

